### ISSUE TITLE
[Easy] Valid Parentheses

### ISSUE THREAD

**Issue by Vishwas2** [Vishwas2/Hacktoberfest2023#15]
Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.

An input string is valid if:

Open brackets must be closed by the same type of brackets.
Open brackets must be closed in the correct order.
Every close bracket has a corresponding open bracket of the same type.
 
Example 1:

Input: s = "()"
Output: true
Example 2:

Input: s = "()[]{}"
Output: true
Example 3:

Input: s = "(]"
Output: false

**Comment by Kaloioanness** [comment]
Assign me @Vishwas2

**Comment by pranav-jadhav** [comment]
@Vishwas2 Please assign this issue to me

**Comment by Vishwas2** [comment]
@Kaloioanness I have assigned this to you.

**Comment by Vishwas2** [comment]
@pranav-jadhav I have assigned this to you. Please give a ⭐ to the repo to show your support.

**Comment by abhinab-choudhury** [comment]
This how you do open-source !!! INTERESTING

**Comment by abhinab-choudhury** [comment]
This how you do open-source !!! INTERESTING

**Comment by Jatingupta9120** [comment]
please assign this issue to me
