### ISSUE TITLE
[Easy] Merge Two Sorted Lists

### ISSUE THREAD

**Issue by Vishwas2** [Vishwas2/Hacktoberfest2023#16]
You are given the heads of two sorted linked lists list1 and list2.

Merge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists.

Return the head of the merged linked list.

**Comment by Milind-Palaria** [comment]
hey @Vishwas2, can you assign me?

**Comment by V-M-Tejus** [comment]
can you assign this to me

**Comment by pranav-jadhav** [comment]
@Vishwas2 Assign this issue to me

**Comment by Vishwas2** [comment]
@pranav-jadhav @Milind-Palaria @V-M-Tejus I have assigned this to the three of you. Please give a ⭐ to the repo to show your support.

**Comment by Sahasri02** [comment]
hey there ,can you assign me this

**Comment by Vishwas2** [comment]
@Sahasri02 I have assigned the issue to you😊. Please read CONTRIBUTING.md to understand how to contribute to this repo and do give a ⭐ to the repo to show your support.
