### ISSUE TITLE
[Medium] Peak Index in a Mountain Array

### ISSUE THREAD

**Issue by rajiv57** [Vishwas2/Hacktoberfest2023#33]
An array arr is a mountain if the following properties hold:

arr.length >= 3
There exists some i with 0 < i < arr.length - 1 such that:
arr[0] < arr[1] < ... < arr[i - 1] < arr[i] 
arr[i] > arr[i + 1] > ... > arr[arr.length - 1]
Given a mountain array arr, return the index i such that arr[0] < arr[1] < ... < arr[i - 1] < arr[i] > arr[i + 1] > ... > arr[arr.length - 1].

You must solve it in O(log(arr.length)) time complexity.

 

Example 1:

Input: arr = [0,1,0]
Output: 1
Example 2:

Input: arr = [0,2,1,0]
Output: 1
Example 3:

Input: arr = [0,10,5,2]
Output: 1
 

Constraints:

3 <= arr.length <= 105
0 <= arr[i] <= 106
arr is guaranteed to be a mountain array.

**Comment by rajiv57** [comment]
i want to work on this issue please assign this to me

**Comment by Vishwas2** [comment]
@rajiv57 I have assigned this to you. Please read CONTRIBUTING.md to understand how to properly contribute to this repo 😁.

**Comment by rajiv57** [comment]
i have made a pr
