### ISSUE TITLE
Palindrome Number

### ISSUE THREAD

**Issue by UsarVR** [Vishwas2/Hacktoberfest2023#4]
I want to solve easy Question 9 of leetcode on palindrome number. Please assign this to me .

**Comment by Vishwas2** [comment]
I have assigned this to you. You may start working on the problem 😁.

**Comment by gulatikeshav** [comment]
Please assign me this issue

**Comment by gulatikeshav** [comment]
I have made the PR #24

**Comment by Vishwas2** [comment]
@gulatikeshav I have assigned this issue to you. Please ⭐ mark this repo to show your support 😊.
