### ISSUE TITLE
[Easy] Leetcode 704:Binary search in java

### ISSUE THREAD

**Issue by priyanshu8584** [Vishwas2/Hacktoberfest2023#41]

**Comment by priyanshu8584** [comment]
assign this issue to me

**Comment by Vishwas2** [comment]
write the difficulty level and the question and make sure that this problem hasn't already been solved then I will assign it to you.

**Comment by priyanshu8584** [comment]
difficulty level added

**Comment by Vishwas2** [comment]
@priyanshu8584 I have assigned this to you 😊 . Please read CONTRIBUTING.md to understand how to contribute to this repo and please give this repo a ⭐to show your support.

**Comment by Vishwas2** [comment]
> Given an array of integers nums which is sorted in ascending order, and an integer target, write a function to search target in nums. If target exists, then return its index. Otherwise, return -1.
> 
> You must write an algorithm with O(log n) runtime complexity.
> 
> Example 1:
> 
> Input: nums = [-1,0,3,5,9,12], target = 9 Output: 4 Explanation: 9 exists in nums and its index is 4 Example 2:
> 
> Input: nums = [-1,0,3,5,9,12], target = 2 Output: -1 Explanation: 2 does not exist in nums so return -1
> 
> Constraints:
> 
> 1 <= nums.length <= 104 -104 < nums[i], target < 104 All the integers in nums are unique. nums is sorted in ascending order.

I meant that you have to write the question before the answer as comment not here. I have written the question for you and merged your pr.
