### ISSUE TITLE
[Easy] Merge Two sorted list

### ISSUE THREAD

**Issue by Ishika0-0** [Vishwas2/Hacktoberfest2023#48]
/*You are given the heads of two sorted linked lists list1 and list2.

Merge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists.

Return the head of the merged linked list.*/

Can I solve this problem

**Comment by Ishika0-0** [comment]
@Vishwas2 Can I contribute to this issue

**Comment by Vishwas2** [comment]
@Ishika0-0 This question has already been solved.
