### ISSUE TITLE
Reverse Integer

### ISSUE THREAD

**Issue by Pakeetharan** [Vishwas2/Hacktoberfest2023#5]
Given a signed 32-bit integer x, return x with its digits reversed. If reversing x causes the value to go outside the signed 32-bit integer range [-231, 231 - 1], then return 0.

Assume the environment does not allow you to store 64-bit integers (signed or unsigned).

Example 1:

Input: x = 123
Output: 321
Example 2:

Input: x = -123
Output: -321
Example 3:

Input: x = 120
Output: 21
 

Constraints:

-231 <= x <= 231 - 1

**Comment by Vishwas2** [comment]
What is the difficulty level of this question?

**Comment by Pakeetharan** [comment]
> What is the difficulty level of this question?

Medium

**Comment by Vishwas2** [comment]
I have assigned this issue to you. You may start working on it😊. Please star the repository to show your support.
