### ISSUE TITLE
[Medium] Maximum Subarray

### ISSUE THREAD

**Issue by imbeshat** [Vishwas2/Hacktoberfest2023#51]
Given an integer array nums, find the subarray with the largest sum, and return its sum.

Example 1:

Input: nums = [-2,1,-3,4,-1,2,1,-5,4]
Output: 6
Explanation: The subarray [4,-1,2,1] has the largest sum 6.
Example 2:

Input: nums = [1]
Output: 1
Explanation: The subarray [1] has the largest sum 1.
Example 3:

Input: nums = [5,4,-1,7,8]
Output: 23
Explanation: The subarray [5,4,-1,7,8] has the largest sum 23.
 
Constraints:

1 <= nums.length <= 105
-104 <= nums[i] <= 104

### Thanks.

**Comment by Jatingupta9120** [comment]
please assign this issue to me i will solve in less time complexity

**Comment by Vishwas2** [comment]
@Jatingupta9120 I have assigned this to you 😊 . Please read CONTRIBUTING.md to understand how to contribute to this repo and please give this repo a ⭐to show your support.
