### ISSUE TITLE
[Medium] Perfect Squares

### ISSUE THREAD

**Issue by Baron105** [Vishwas2/Hacktoberfest2023#57]
[Link](https://leetcode.com/problems/perfect-squares/)

Given an integer n, return the least number of perfect square numbers that sum to n.

A perfect square is an integer that is the square of an integer; in other words, it is the product of some integer with itself. For example, 1, 4, 9, and 16 are perfect squares while 3 and 11 are not.

Example 1:
Input: n = 12
Output: 3
Explanation: 12 = 4 + 4 + 4.

Example 2:
Input: n = 13
Output: 2
Explanation: 13 = 4 + 9.

Constraints:
1 <= n <= 10^4

**Comment by Vishwas2** [comment]
@Baron105 I have assigned this to you😊

**Comment by Jatingupta9120** [comment]
assign this issue to me

**Comment by Baron105** [comment]
Closing this issue as the linked PR #68  has been accepted and merged already. Thanks @Vishwas2 for assigning!
