### ISSUE TITLE
[Easy] Reverse Integer

### ISSUE THREAD

**Issue by Ishika0-0** [Vishwas2/Hacktoberfest2023#63]
/*Given a signed 32-bit integer x, return x with its digits reversed. If reversing x causes the value to go outside the signed 32-bit integer range [-231, 231 - 1], then return 0.

Assume the environment does not allow you to store 64-bit integers (signed or unsigned).*/

**Comment by Ishika0-0** [comment]
@Vishwas2 Can I contribute to this issue

**Comment by Vishwas2** [comment]
@Ishika0-0 I have assigned this to you 😊 . Please read CONTRIBUTING.md to understand how to contribute to this repo and please give this repo a ⭐to show your support.

**Comment by prithu12** [comment]
can you assign to me

**Comment by Vishwas2** [comment]
@prithu12 I have assigned this to you 😊 . Please read CONTRIBUTING.md to understand how to contribute to this repo and please give this repo a ⭐to show your support.

**Comment by shreyanshig** [comment]
Hi @Ishika0-0 @Vishwas2 , Could you please this task to me?

**Comment by Jatingupta9120** [comment]
assign this issue to me

**Comment by Vishwas2** [comment]
@shreyanshig @Jatingupta9120 I have assigned this to you 😊 . Please read CONTRIBUTING.md to understand how to contribute to this repo and please give this repo a ⭐to show your support.

**Comment by Divyansh200102** [comment]
please assign this to me @Vishwas2
