### ISSUE TITLE
[Easy] Length Of Last Word 

### ISSUE THREAD

**Issue by AmalCodin** [Vishwas2/Hacktoberfest2023#69]
Given a string s consisting of words and spaces, return the length of the last word in the string.

A word is a maximal substring consisting of non-space characters only.

Example 1:

Input: s = "Hello World"
Output: 5
Explanation: The last word is "World" with length 5.

Example 2:

Input: s = "   fly me   to   the moon  "
Output: 4
Explanation: The last word is "moon" with length 4.
Example 3:

Input: s = "luffy is still joyboy"
Output: 6
Explanation: The last word is "joyboy" with length 6.
 

Constraints:

1 <= s.length <= 104
s consists of only English letters and spaces ' '.
There will be at least one word in s.

**Comment by AmalCodin** [comment]
Can I contribute to this issue ?

**Comment by Vishwas2** [comment]
@AmalCodin I have assigned this to you 😊 . Please read CONTRIBUTING.md to understand how to contribute to this repo and please give this repo a ⭐to show your support.

**Comment by shreyanshig** [comment]
Hi @Vishwas2, Could you please assign this issue to me?

**Comment by Jatingupta9120** [comment]
assign this isssue to me

**Comment by Vishwas2** [comment]
@shreyanshig I have assigned this issue to you.
