### ISSUE TITLE
[Easy]  Happy Number

### ISSUE THREAD

**Issue by Akshayp02** [Vishwas2/Hacktoberfest2023#81]
What would you like to Propose?
The purpose of the problem is to test your ability to manipulate linked lists algorithm design abilities, and problem-solving capabilities, making it a valuable exercise for honing your programming skills. and perform operations on them efficiently.

This problem serves several purposes:

Algorithmic Proficiency:
Problem-Solving Skills:
Efficiency:
Boundary Testing
Follow-up Challenge:

Issue details

Write an algorithm to determine if a number n is happy. (Asked in Google Question)

A happy number is a number defined by the following process:

Starting with any positive integer, replace the number by the sum of the squares of its digits.
Repeat the process until the number equals 1 (where it will stay), or it loops endlessly in a cycle which does not include 1.
Those numbers for which this process ends in 1 are happy.
Return true if n is a happy number, and false if not.

Example 1:

Input: n = 19
Output: true
Explanation:
12^2 + 92^2 = 82
82^2 + 22^2 = 68
62^2 + 82^2 = 100
12^2 + 02^2 + 02^2 = 1
Example 2:

Input: n = 2
Output: false
 

Constraints:

1 <= n <= 231 - 1

**Comment by Vishwas2** [comment]
@Akshayp02 I have assigned this to you. Please read the documentation to understand how to contribute to this repo 😊.
