### ISSUE TITLE
[Medium] Longest Increasing Subsequence

### ISSUE THREAD

**Issue by Sagar-Mondal** [Vishwas2/Hacktoberfest2023#87]
Given an integer array nums, return the length of the longest strictly increasing 
subsequence.

Example 1:

Input: nums = [10,9,2,5,3,7,101,18]
Output: 4
Explanation: The longest increasing subsequence is [2,3,7,101], therefore the length is 4.
Example 2:

Input: nums = [0,1,0,3,2,3]
Output: 4
Example 3:

Input: nums = [7,7,7,7,7,7,7]
Output: 1
 

Constraints:

1 <= nums.length <= 2500
-10^4 <= nums[i] <= 10^4

Follow up: Can you come up with an algorithm that runs in O(n log(n)) time complexity?

**Comment by Sagar-Mondal** [comment]
@Vishwas2 Please assign me this issue.

**Comment by Vishwas2** [comment]
@Sagar-Mondal I have assigned this to you 😊 . Please read CONTRIBUTING.md to understand how to contribute to this repo.

**Comment by Divyansh200102** [comment]
i want to work on this issue

**Comment by Sagar-Mondal** [comment]
@Vishwas2 I have already made the pull request according to CONTRIBUTING.md . Kindly merge it. Thank you.
