### ISSUE TITLE
[Easy]  Container With Most Water

### ISSUE THREAD

**Issue by mahfouz72** [Vishwas2/Hacktoberfest2023#89]
[link](https://leetcode.com/problems/container-with-most-water/)

You are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the ith line are (i, 0) and (i, height[i]).

Find two lines that together with the x-axis form a container, such that the container contains the most water.

Return the maximum amount of water a container can store.

Notice that you may not slant the container.

**Comment by mahfouz72** [comment]
@Vishwas2 assign this issue to me

**Comment by Vishwas2** [comment]
@mahfouz72 I have assigned this to you 😊 . Please read CONTRIBUTING.md to understand how to contribute to this repo and please give this repo a ⭐to show your support.

**Comment by Divyansh200102** [comment]
assign me the issue please @Vishwas2

**Comment by Vishwas2** [comment]
@Divyansh200102 I have assigned this to you.
